import rtconfig
from building import *
import os

cwd  = GetCurrentDir()
path = [cwd]
src  = Glob('*.c')

group = DefineGroup('lwrb', src, depend = ['APP_USING_LWRB'], CPPPATH = path)

Return('group')
